###
### Post with node in mongo
###

POST http://localhost:3000/api/cities
Content-Type: application/json


{
	"name": "Nombre de la Ciudad3",
	"country": "País",
	"img": "URL de la imagen",
	"description": "Descripción de la ciudad",
	"itinerary": []
} 


###
###Post itinerary .   title,img,user,price,hashtags,comments,likes,activities
###

POST http://localhost:3000/api/itinerary
Content-Type: application/json

{
	"title": "Título del día",
	"img": "URL de la imagen",
	"user": "Usuario",
	"price": 100,
	"hashtags": ["viaje", "aventura"],
	"comments": ["Comentario 1", "Comentario 2"],
	"likes": 0,
	"activities": ["Actividad 1", "Actividad 2"]
} 
###
###  post city + itinerary
###

POST http://localhost:3000/api/cities
Content-Type: application/json

{
	"name": "Nombre de la Ciudad3",
	"country": "País",
	"img": "URL de la imagen",
	"description": "Descripción de la ciudad",
	"itinerary": {
		"title": "Título del itinerario",
		"img": "URL de la imagen",
		"user": "Usuario",
		"price": 100,
		"hashtags": ["viaje", "aventura"],
		"comments": ["Comentario 1", "Comentario 2"],
		"likes": 0,
		"activities": ["Actividad 1", "Actividad 2"]
	}
}

###
###  get cities
###

GET http://localhost:3000/api/cities
